# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - training36webapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://training36.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_eaa03803faf0478e924b7626ac148162 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a7f305e28789442e9eb19e3989dd12b9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: training36.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eaa03803faf0478e924b7626ac148162 }}/webimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'training36webapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c3929a12e69542ccb25b2d002647e998 }}
        images: 'training36.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_eaa03803faf0478e924b7626ac148162 }}/webimage:${{ github.sha }}'